### ISSUE TITLE
index.md のサブモジュールのリンクが切れている

### ISSUE THREAD

**Issue by taku-n** [tkamenoko/inari#1]
[こちら](https://github.com/taku-n/mikumo/blob/f58f894285d17cc8cecc3e824c111605b299d384/doc/mikumo/index.md)がサンプルなのですが  
Submodules のリンクが，両方とも切れてしまいます  
(.md を付加する必要がある (?))

**Comment by tkamenoko** [comment]
@taku-n 連絡ありがとうございます
v0.2.1 でリンク生成の不具合を修正しました
